ALTER TABLE HOUSE ADD COLUMN NEAREST_STATION_TO_HSR_ZHUBEI VARCHAR(100) DEFAULT NULL;
ALTER TABLE HOUSE ADD COLUMN NEAREST_STATION_TO_FENGYUAN VARCHAR(100) DEFAULT NULL;
ALTER TABLE HOUSE ADD COLUMN WALK_METERS_TO_ELEMENTARY INT DEFAULT NULL;
ALTER TABLE HOUSE ADD COLUMN NEAREST_ELEMENTARY_SCHOOL VARCHAR(100) DEFAULT NULL;
ALTER TABLE HOUSE ADD COLUMN WALK_METERS_TO_JUNIOR_HIGH INT DEFAULT NULL;
ALTER TABLE HOUSE ADD COLUMN NEAREST_JUNIOR_HIGH_SCHOOL VARCHAR(100) DEFAULT NULL;
