-- 重新平衡評分維度權重：
-- 「地點與交通」40%、「生活機能」15%、「價格性價比」15%
-- 其他 5 項按原比例（59%）等比縮減至 30%
UPDATE RATING_DIMENSION SET WEIGHT = 0.4000 WHERE DIMENSION_NAME = '地點與交通';
UPDATE RATING_DIMENSION SET WEIGHT = 0.0900 WHERE DIMENSION_NAME = '格局與空間感';
UPDATE RATING_DIMENSION SET WEIGHT = 0.0700 WHERE DIMENSION_NAME = '採光與通風';
UPDATE RATING_DIMENSION SET WEIGHT = 0.1500 WHERE DIMENSION_NAME = '生活機能';
UPDATE RATING_DIMENSION SET WEIGHT = 0.0700 WHERE DIMENSION_NAME = '社區環境與管理';
UPDATE RATING_DIMENSION SET WEIGHT = 0.1500 WHERE DIMENSION_NAME = '價格性價比';
UPDATE RATING_DIMENSION SET WEIGHT = 0.0500 WHERE DIMENSION_NAME = '屋況與裝潢';
UPDATE RATING_DIMENSION SET WEIGHT = 0.0200 WHERE DIMENSION_NAME = '整體主觀感受';
