CREATE TABLE HOUSE (
    HOUSE_ID            BIGINT          NOT NULL AUTO_INCREMENT,
    NICKNAME            VARCHAR(100)    NOT NULL,
    ADDRESS             VARCHAR(500),
    COMMUNITY_NAME      VARCHAR(200),
    BUILDER             VARCHAR(200),
    HOUSE_AGE_YEAR      INT,
    FLOOR               INT,
    TOTAL_FLOOR         INT,
    BUILD_AREA_PING     DECIMAL(10, 2),
    INDOOR_PING         DECIMAL(10, 2),
    BEDROOM_COUNT       INT,
    LIVING_ROOM_COUNT   INT,
    BATHROOM_COUNT      INT,
    TOTAL_PRICE         DECIMAL(12, 2),
    PARKING_TYPE        VARCHAR(30),
    PARKING_PRICE       DECIMAL(10, 2)  DEFAULT 0,
    MONTHLY_FEE         DECIMAL(10, 2),
    NOTE                TEXT,
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    ELIMINATED_REASON   TEXT,
    CREATED_AT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_HOUSE PRIMARY KEY (HOUSE_ID)
);

CREATE TABLE MEMBER (
    MEMBER_ID       BIGINT          NOT NULL AUTO_INCREMENT,
    DISPLAY_NAME    VARCHAR(100)    NOT NULL,
    ROLE            VARCHAR(50),
    WEIGHT          DECIMAL(5, 4)   NOT NULL,
    SORT_ORDER      INT             NOT NULL DEFAULT 0,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE FILTER_RULE (
    RULE_ID     BIGINT          NOT NULL AUTO_INCREMENT,
    RULE_NAME   VARCHAR(200)    NOT NULL,
    RULE_TYPE   VARCHAR(50)     NOT NULL,
    NUM_VALUE   DECIMAL(12, 2),
    STR_VALUE   VARCHAR(500),
    IS_ACTIVE   BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_FILTER_RULE PRIMARY KEY (RULE_ID)
);

CREATE TABLE RATING_DIMENSION (
    DIMENSION_ID    BIGINT          NOT NULL AUTO_INCREMENT,
    DIMENSION_NAME  VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    WEIGHT          DECIMAL(5, 4)   NOT NULL,
    SORT_ORDER      INT             NOT NULL DEFAULT 0,
    IS_ACTIVE       BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_RATING_DIMENSION PRIMARY KEY (DIMENSION_ID)
);

CREATE TABLE HOUSE_RATING (
    RATING_ID       BIGINT  NOT NULL AUTO_INCREMENT,
    HOUSE_ID        BIGINT  NOT NULL,
    MEMBER_ID       BIGINT  NOT NULL,
    DIMENSION_ID    BIGINT  NOT NULL,
    SCORE           INT     NOT NULL,
    UPDATED_AT      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_HOUSE_RATING  PRIMARY KEY (RATING_ID),
    CONSTRAINT UQ_HOUSE_RATING  UNIQUE (HOUSE_ID, MEMBER_ID, DIMENSION_ID),
    CONSTRAINT FK_RATING_HOUSE      FOREIGN KEY (HOUSE_ID)      REFERENCES HOUSE(HOUSE_ID)              ON DELETE CASCADE,
    CONSTRAINT FK_RATING_MEMBER     FOREIGN KEY (MEMBER_ID)     REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_RATING_DIMENSION  FOREIGN KEY (DIMENSION_ID)  REFERENCES RATING_DIMENSION(DIMENSION_ID)
);
