-- 移除舊的「實價登錄估計總價」欄位與「實價登錄成交資料表」整套功能；
-- 改為使用者手動填寫的「過去一年實登不含車位每坪」上下限（萬/坪）。

ALTER TABLE HOUSE DROP COLUMN ESTIMATED_REGISTRY_PRICE;

DROP TABLE IF EXISTS REAL_PRICE_RECORD;

ALTER TABLE HOUSE
    ADD COLUMN REGISTRY_PRICE_PER_PING_MIN DECIMAL(10, 2) NULL COMMENT '過去一年實登不含車位每坪下限（萬/坪，使用者手填）' AFTER DISCOUNT_PERCENT,
    ADD COLUMN REGISTRY_PRICE_PER_PING_MAX DECIMAL(10, 2) NULL COMMENT '過去一年實登不含車位每坪上限（萬/坪，使用者手填）' AFTER REGISTRY_PRICE_PER_PING_MIN;
