-- 1. House 新增 WARNING_REASON 欄位（可修缮缺陷觸發後的警告訊息）
ALTER TABLE HOUSE ADD COLUMN WARNING_REASON TEXT DEFAULT NULL;

-- 2. 把現有的 EXCLUDE_VISIT_ISSUES 規則升級為 EXCLUDE_FATAL_VISIT_ISSUES（只淘汰致命缺陷）
UPDATE FILTER_RULE
SET RULE_TYPE = 'EXCLUDE_FATAL_VISIT_ISSUES'
WHERE RULE_TYPE = 'EXCLUDE_VISIT_ISSUES';

-- 3. 新增 WARN_REPAIRABLE_VISIT_ISSUES 規則（可修缮缺陷只警告）
INSERT INTO FILTER_RULE (RULE_NAME, RULE_TYPE, NUM_VALUE, STR_VALUE, IS_ACTIVE)
VALUES ('可修缮缺陷警告', 'WARN_REPAIRABLE_VISIT_ISSUES', NULL, NULL, TRUE);
