-- 看房評估欄位
ALTER TABLE HOUSE
  ADD COLUMN HAS_MOLD_OR_LEAK         BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN IS_FLOOR_LEVEL_OK        BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN IS_DOOR_WINDOW_OK        BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN IS_WATER_PRESSURE_OK     BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN ELECTRIC_CAPACITY        INT         NULL DEFAULT NULL,
  ADD COLUMN IS_HAUNTED               BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN IS_SEA_SAND              BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN IS_RADIATION             BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN HAS_ILLEGAL_CONSTRUCTION BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN FLOOD_RISK               VARCHAR(20) NULL DEFAULT NULL,
  ADD COLUMN HAS_NUISANCE_FACILITY    BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN NUISANCE_FACILITY_NOTE   TEXT        NULL,
  ADD COLUMN IS_MANAGEMENT_OK         BOOLEAN     NULL DEFAULT NULL,
  ADD COLUMN VISIT_DATE               DATE        NULL DEFAULT NULL,
  ADD COLUMN VISIT_IMPRESSION         TEXT        NULL;
