steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/double-scholar-205705/besthouse/backend'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/double-scholar-205705/besthouse/backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'besthouse-backend'
      - '--image'
      - 'asia-east1-docker.pkg.dev/double-scholar-205705/besthouse/backend'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'

images:
  - 'asia-east1-docker.pkg.dev/double-scholar-205705/besthouse/backend'
